# Generated by Django 3.2.12 on 2022-02-09 12:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('nvv', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_nvv', models.DateField(db_index=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rut', models.CharField(db_index=True, max_length=13)),
                ('cliente', models.CharField(db_index=True, max_length=200)),
                ('tipo_despacho', models.CharField(default='DIMACO', max_length=200)),
                ('comuna', models.CharField(db_index=True, max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('nombre_contacto', models.CharField(max_length=200)),
                ('telefono_contacto', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('condicion_pago', models.CharField(max_length=100)),
                ('comprobante_pago', models.FileField(blank=True, upload_to='comprobantes_de_pago/%Y/%m/%d/')),
                ('observacion', models.CharField(blank=True, max_length=2500)),
                ('fecha_despacho', models.DateField(db_index=True)),
                ('fecha_despacho_final', models.DateField(db_index=True)),
                ('hora_de_despacho_inicio', models.TimeField()),
                ('hora_de_despacho_fin', models.TimeField()),
                ('hora_despacho_extra_inicio', models.TimeField()),
                ('hora_despacho_extra_fin', models.TimeField()),
                ('rango_horario_final', models.IntegerField(choices=[(0, ''), (1, 'AM'), (2, 'PM')], default=0)),
                ('estado', models.IntegerField(choices=[(0, 'En Preparación'), (1, 'Preparado'), (2, 'Tubos'), (3, 'Cañería'), (4, 'Rollos')], default=0)),
                ('observacion_despacho', models.CharField(blank=True, max_length=2500)),
                ('numero_guia', models.CharField(blank=True, max_length=100)),
                ('documento_salida', models.FileField(default='None', upload_to='voucher_de_despacho/%Y/%m/%d/')),
                ('nombre_vendedor', models.CharField(db_index=True, max_length=200)),
                ('nombre_asistente', models.CharField(db_index=True, max_length=200)),
                ('listo', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0)),
                ('estado_pedido_para_vendedor', models.IntegerField(choices=[(0, 'En Preparación'), (1, 'Detenido'), (2, 'Preparado incompleto'), (3, 'Preparado completo')], default=0)),
                ('valor_neto_documento', models.IntegerField(default=0)),
            ],
        ),
    ]
