# Generated by Django 4.0 on 2022-01-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('nvv', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_nvv', models.DateField(db_index=True)),
                ('fecha_solicitud', models.DateField(auto_now_add=True, db_index=True)),
                ('rut', models.CharField(db_index=True, max_length=12)),
                ('cliente', models.CharField(db_index=True, max_length=200)),
                ('direccion', models.CharField(max_length=250)),
                ('comuna', models.CharField(db_index=True, max_length=50)),
                ('nombre_contacto', models.CharField(max_length=200)),
                ('telefono_contacto', models.CharField(max_length=12)),
                ('condicion_pago', models.CharField(max_length=100)),
                ('comprobante_pago', models.FileField(blank=True, upload_to='comprobantes_de_pago/%Y/%m/%d/')),
                ('observacion', models.CharField(blank=True, max_length=2500)),
                ('fecha_despacho', models.DateField(db_index=True)),
                ('hora_de_despacho', models.TimeField()),
                ('fecha_entregado', models.DateField(blank=True, db_index=True)),
                ('estado', models.IntegerField(choices=[(0, 'En Preparación'), (1, 'Preparado'), (2, 'Despachado')], default=0)),
                ('completado', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0)),
                ('observacion_despacho', models.CharField(blank=True, max_length=2500)),
                ('documento_salida', models.FileField(blank=True, upload_to='documentos_de_salida/%Y/%m/%d/')),
                ('numero', models.IntegerField(db_index=True)),
            ],
        ),
    ]
