# Generated by Django 4.0 on 2022-01-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMejoraDespacho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes',
            name='rut',
            field=models.CharField(db_index=True, max_length=13),
        ),
    ]
