# Generated by Django 4.0 on 2022-01-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMejoraDespacho', '0002_alter_ordenes_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes',
            name='documento_salida',
            field=models.FileField(default='None', upload_to='documentos_de_salida/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='fecha_entregado',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='numero',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='observacion_despacho',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
