# Generated by Django 4.0 on 2022-01-05 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppMejoraDespacho', '0005_alter_ordenes_observacion_despacho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes',
            name='fecha_entregado',
            field=models.DateField(blank=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
