# Generated by Django 4.0 on 2022-01-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMejoraDespacho', '0008_remove_ordenes_hora_de_despacho_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenes',
            name='completado',
        ),
    ]
