# Generated by Django 4.0 on 2022-01-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMejoraDespacho', '0009_remove_ordenes_completado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
