# Generated by Django 4.0 on 2022-01-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMejoraDespacho', '0010_alter_ordenes_fecha_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes',
            name='hora_despacho_extra_fin',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenes',
            name='hora_despacho_extra_inicio',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
