# Generated by Django 4.0 on 2022-01-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMejoraDespacho', '0015_alter_ordenes_documento_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes',
            name='nombre_asistente',
            field=models.CharField(db_index=True, default='uwu', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenes',
            name='nombre_vendedor',
            field=models.CharField(db_index=True, default='uwuwu', max_length=200),
            preserve_default=False,
        ),
    ]
