# Generated by Django 4.0 on 2022-01-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMejoraDespacho', '0016_ordenes_nombre_asistente_ordenes_nombre_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes',
            name='listo',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0),
        ),
    ]
