# Generated by Django 4.0 on 2022-01-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMejoraDespacho', '0017_ordenes_listo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes',
            name='valor_neto_documento',
            field=models.IntegerField(default=0),
        ),
    ]
