# Generated by Django 4.0 on 2022-01-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMejoraDespacho', '0018_ordenes_valor_neto_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenes',
            name='region',
        ),
        migrations.AddField(
            model_name='ordenes',
            name='tipo_despacho',
            field=models.IntegerField(choices=[(0, 'DIMACO'), (1, 'Externo')], default=0),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='comuna',
            field=models.IntegerField(choices=[(0, 'Alhué'), (1, 'Buin'), (2, 'Calera de Tango'), (3, 'Cerrillo'), (4, 'Cerro Navia'), (5, 'Curacaví'), (6, 'El Bosque'), (7, 'El Monte'), (8, 'Estación Central'), (9, 'Isla de Maipo'), (10, 'La Cisterna'), (11, 'La Florida'), (12, 'La Granja'), (13, 'La Pintana'), (14, 'Lo Espejo'), (15, 'Lo Prado'), (16, 'Macul'), (17, 'Maipú'), (18, 'María Pinto'), (19, 'Melipilla'), (20, 'Padre Hurtado'), (21, 'Paine'), (22, 'Pedro Aguirre Cerda'), (23, 'Peñaflor'), (24, 'Peñalolén'), (25, 'Pirque'), (26, 'Puente Alto'), (27, 'Quinta Normal'), (28, 'San Bernardo'), (29, 'San Joaquín'), (30, 'San José de Maipo'), (31, 'San Miguel'), (32, 'San Pedro'), (33, 'San Ramón'), (34, 'Talagante')], db_index=True),
        ),
    ]
