# Generated by Django 4.0 on 2022-01-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMejoraDespacho', '0019_remove_ordenes_region_ordenes_tipo_despacho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes',
            name='comuna',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
