# Generated by Django 4.0 on 2022-01-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMejoraDespacho', '0020_alter_ordenes_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes',
            name='tipo_despacho',
            field=models.CharField(default='DIMACO', max_length=200),
        ),
    ]
