# Generated by Django 4.0 on 2022-01-24 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMejoraDespacho', '0021_alter_ordenes_tipo_despacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes',
            name='estado_pedido_para_vendedor',
            field=models.IntegerField(choices=[(0, 'En Preparación'), (1, 'Sin pago adjunto'), (2, 'Sin material'), (3, 'Preparado incompleto'), (4, 'Preparado completo')], default=0),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='fecha_despacho_final',
            field=models.DateField(db_index=True, default=datetime.date(2022, 1, 24)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenes',
            name='rango_horario_final',
            field=models.IntegerField(choices=[(0, ''), (1, 'AM'), (2, 'PM')], default=0),
        ),
    ]
