# Generated by Django 4.0.4 on 2022-05-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMejoraDespacho', '0023_alter_ordenes_estado_pedido_para_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes',
            name='estado',
            field=models.IntegerField(choices=[(0, 'En Preparación'), (1, 'Preparado'), (2, 'Tubos'), (3, 'Cañería'), (4, 'Rollos'), (5, 'Flejes'), (6, 'Planchas'), (7, 'Tubos Acero'), (8, 'Pletina'), (9, 'Soldadura'), (20, 'En espera')], default=0),
        ),
    ]
